---
version: "3.5"

x-app: &app
  build:
    context: .
    dockerfile: ./Dockerfile
  environment: &env
    NODE_ENV: development
    RAILS_ENV: ${RAILS_ENV:-development}
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - bundle:/usr/local/bundle
    - ./node_modules:/app/node_modules:cached
    - packs:/app/public/packs
    - rails_cache:/app/tmp/cache
  environment:
    <<: *env
    DATABASE_URL: postgres://postgres:postgres@postgres:5432
    BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
    WEBPACKER_DEV_SERVER_HOST: webpacker
    WEB_CONCURRENCY: 1
    HISTFILE: /app/log/.bash_history
    PSQL_HISTFILE: /app/log/.psql_history
  depends_on:
    postgres:
      condition: service_healthy

services:
  backend:
    <<: *backend

  runner:
    <<: *backend
    command: /bin/bash
    ports:
      - "3000:3000"
      - "3002:3002"

  rails:
    <<: *backend
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - 3000

  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

  webpacker:
    <<: *app
    command: ./bin/webpack-dev-server
    ports:
      - 3035
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle
      - ./node_modules:/app/node_modules:cached
      - packs:/app/public/packs
    environment:
      <<: *env
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0

volumes:
  postgres:
  bundle:
  node_modules:
  rails_cache:
  packs:
